services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=your_password_db
   
    ports:
      - "5539:5432"
    volumes:
      - /root/postgresql/data:/var/lib/postgresql/data
 
    restart: unless-stopped
    networks:
      - internal_shared_net

networks:
  internal_shared_net:
    external: true

