services:
  odoo_container:
    container_name: odoo_15
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8869:8069"   
      - "8872:8072"  
    volumes:
      - ./custom-addons:/opt/odoo15/custom-addons/  
      - ./logs:/var/log/odoo/
      - ./config/odoo15.conf:/etc/odoo15.conf
      - ./odoo-data:/opt/odoo15/.local/share/Odoo/
      - ./lib:/opt/odoo15/.local/lib
      - ./bin:/opt/odoo15/.local/bin
    restart: unless-stopped
    networks:
      - internal_shared_net
    
networks:
  internal_shared_net: 
    external: true






