services:
  odoo_container:
    container_name: odoo_16
    build:
      context: .
      dockerfile: Dockerfile            
    ports:
      - "9969:8069"   
      - "9972:8072"  
    volumes:
      - ./custom-addons:/opt/odoo16/custom-addons/  
      - ./logs:/var/log/odoo/
      - ./config/odoo16.conf:/etc/odoo16.conf
      - ./odoo-data:/opt/odoo16/.local/share/Odoo/
      - ./lib:/opt/odoo16/.local/lib
      - ./bin:/opt/odoo16/.local/bin
    restart: unless-stopped
    networks:
      - internal_shared_net
    
networks:
  internal_shared_net: 
    external: true

